root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe cmd/api/main.go"
bin = "tmp/main.exe"
delay = 1000
kill_delay = 500
log = "build.log"

[log]
time = true

[watch]
include = ["."]
exclude = ["tmp", "vendor"]

[env]
file = ".env"

